import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { SiteHeader } from '../../components/site-header';
import { getAllConcepts, getConceptBySlug, getConceptHref, getConceptScope, getConceptTitle } from '@/lib/concepts';
import { getSurahByNumber, getSurahHref, getTranslation, getVerse } from '@/lib/quran';
import { SourceDrawer } from '@/app/components/source-drawer';
import { getPeopleForVerse, getPersonHref } from '@/lib/people';
import { getPersonName } from '@/lib/person-locale';
import { getQuranPdfSource } from '@/lib/sources';
import { getLocale } from '@/lib/server-locale';
import { localeNumber } from '@/lib/locale';
import { getHadithByIdForLocale } from '@/lib/hadith';

export function generateStaticParams() {
  return getAllConcepts().map((concept) => ({ slug: concept.slug }));
}

type ConceptPageProps = {
  params: Promise<{ slug: string }>;
  searchParams?: Promise<{ verses?: string; hadiths?: string }>;
};

export async function generateMetadata({ params }: ConceptPageProps): Promise<Metadata> {
  const { slug } = await params;
  const concept = getConceptBySlug(slug);
  if (!concept) return {};
  return {
    title: concept.title,
    description: `${concept.title}: ${concept.scope.toLocaleLowerCase('en-US')}.`,
    openGraph: { images: [] },
    twitter: { images: [] },
  };
}

export default async function ConceptPage({ params, searchParams }: ConceptPageProps) {
  const locale = await getLocale();
  const tr = locale === 'tr';
  const { slug } = await params;
  const query = await searchParams;
  const concept = getConceptBySlug(slug);
  if (!concept) notFound();
  const related = concept.related.flatMap((relatedSlug) => {
    const record = getConceptBySlug(relatedSlug);
    return record ? [record] : [];
  });
  const versePageSize = 40;
  const hadithPageSize = 30;
  const versePageCount = Math.max(1, Math.ceil(concept.verseRefs.length / versePageSize));
  const hadithPageCount = Math.max(1, Math.ceil(concept.hadithIds.length / hadithPageSize));
  const versePage = Math.min(versePageCount, Math.max(1, Number.parseInt(query?.verses ?? '1', 10) || 1));
  const hadithPage = Math.min(hadithPageCount, Math.max(1, Number.parseInt(query?.hadiths ?? '1', 10) || 1));
  const displayedVerseRefs = concept.verseRefs.slice((versePage - 1) * versePageSize, versePage * versePageSize);
  const displayedHadithIds = concept.hadithIds.slice((hadithPage - 1) * hadithPageSize, hadithPage * hadithPageSize);
  const people = [...new Map(concept.verseRefs.flatMap((reference) => getPeopleForVerse(reference.surah, reference.ayah)).map((person) => [person.slug, person])).values()];
  const pageHref = (verses: number, hadiths: number, anchor: string) => `/concept/${concept.slug}?verses=${verses}&hadiths=${hadiths}#${anchor}`;

  return (
    <main>
      <SiteHeader />
      <div className="wiki-layout concept-article-layout">
        <aside className="wiki-toc" aria-label={tr ? 'Sayfa içindekileri' : 'Page contents'}><span>{tr ? 'İçindekiler' : 'Contents'}</span><a className="active" href="#introduction">{tr ? 'Giriş' : 'Introduction'}</a><a href="#verses">{tr ? 'İlgili ayetler' : 'Related verses'}</a><a href="#hadiths">{tr ? 'İlgili hadisler' : 'Related hadiths'}</a><a href="#related">{tr ? 'İlgili kavramlar' : 'Related concepts'}</a></aside>
        <article className="wiki-article">
          <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">{tr ? 'Ana sayfa' : 'Main page'}</Link><span>›</span><Link href="/concepts">{tr ? 'Kavramlar' : 'Concepts'}</Link><span>›</span>{getConceptTitle(concept, locale)}</nav>
          <header className="article-header" id="introduction">
            <h1>{getConceptTitle(concept, locale)}</h1>
            <p className="article-arabic-title" lang="ar" dir="rtl">{concept.arabic}</p>
            <p className="article-lead">{tr ? `Bu sayfa ${getConceptTitle(concept, locale).toLocaleLowerCase('tr-TR')} ile ilgili otomatik etiketlenmiş Kur’an ve sahih hadis kayıtlarını bir araya getirir.` : `This article provides unified access to automatically tagged Quran and authentic hadith records concerning ${concept.title.toLocaleLowerCase('en-US')}.`}</p>
          </header>
          <section className="concept-at-a-glance" aria-labelledby="glance-title">
            <span className="reader-overline">{tr ? 'Bir bakışta' : 'At a glance'}</span>
            <h2 id="glance-title">{tr ? 'Kaynak bağlantıları' : `A source trail for ${concept.title.toLocaleLowerCase('en-US')}`}</h2>
            <p>{getConceptScope(concept, locale)}. {tr ? 'Kayıtlar, çok dilli kaynak metinlerinde bütün kelime ve ifade eşleşmeleri taranarak üretilir; ayet numaraları elle seçilmez.' : 'Records are generated by whole-word and phrase matching across the multilingual source corpora; verse IDs are not selected by hand.'}</p>
            <dl><div><dt>{tr ? 'Kur’an kayıtları' : 'Quran records'}</dt><dd>{concept.verseRefs.length.toLocaleString(localeNumber(locale))}</dd></div><div><dt>{tr ? 'Sahih hadisler' : 'Authentic hadiths'}</dt><dd>{concept.hadithIds.length.toLocaleString(localeNumber(locale))}</dd></div><div><dt>{tr ? 'Bağlı kişiler' : 'Connected people'}</dt><dd>{people.length}</dd></div></dl>
          </section>
          <section className="concept-verse-list" id="verses" aria-labelledby="concept-verses-title">
            <h2 id="concept-verses-title">{tr ? 'Kur’an’daki ilgili kayıtlar' : 'Related records in the Quran'}</h2>
            {versePageCount > 1 ? <p className="concept-result-note">{tr ? `${concept.verseRefs.length.toLocaleString('tr-TR')} eşleşme · ${versePage}/${versePageCount}. sayfa` : `${concept.verseRefs.length.toLocaleString('en-US')} matches · page ${versePage} of ${versePageCount}`}</p> : null}
            {displayedVerseRefs.map((reference) => {
              const surah = getSurahByNumber(reference.surah);
              const verse = getVerse(reference.surah, reference.ayah);
              const meaning = getTranslation(reference.surah, reference.ayah, locale);
              if (!surah || !verse || !meaning) throw new Error(`Concept reference is missing: ${reference.surah}:${reference.ayah}`);
              const source = getQuranPdfSource(surah.startOffset + reference.ayah - 1);
              return (
                <article key={`${reference.surah}:${reference.ayah}`}>
                  <h3><Link href={`${getSurahHref(surah)}#verse-${reference.ayah}`}>{surah.nameTransliterated} {reference.surah}:{reference.ayah}</Link></h3>
                  <p className="concept-verse-arabic" lang="ar" dir="rtl">{verse.text}</p>
                  <p>{meaning.text}</p>
                  {meaning.footnotes ? <small>{meaning.footnotes}</small> : null}
                  <div className="concept-source-actions"><SourceDrawer label={tr ? 'Kaynağı aç' : 'View exact source'} title={`${surah.nameTransliterated} ${reference.surah}:${reference.ayah}`} description={tr ? 'QuranEnc Rowwad kaynağındaki doğrulanmış meal kaydı.' : 'Exact page in the official QuranEnc Rowwad mushaf PDF.'} pdfUrl={source?.pdfUrl} page={source?.page} sourceUrl="https://quranenc.com" sourceLabel="QuranEnc" /><Link href={`${getSurahHref(surah)}#verse-${reference.ayah}`}>{tr ? 'Tam ayet makalesini aç' : 'Open full verse article'}</Link></div>
                </article>
              );
            })}
            {versePageCount > 1 ? <nav className="concept-pagination" aria-label={tr ? 'Ayet kayıt sayfaları' : 'Verse record pages'}>
              {versePage > 1 ? <Link href={pageHref(versePage - 1, hadithPage, 'verses')}>← {tr ? 'Önceki ayetler' : 'Previous verses'}</Link> : <span />}
              {versePage < versePageCount ? <Link href={pageHref(versePage + 1, hadithPage, 'verses')}>{tr ? 'Sonraki ayetler' : 'Next verses'} →</Link> : null}
            </nav> : null}
          </section>
          {concept.hadithIds.length > 0 ? <section className="concept-related-records" id="hadiths" aria-labelledby="concept-hadiths-title"><h2 id="concept-hadiths-title">{tr ? 'İlgili sahih hadisler' : 'Related authentic hadiths'}</h2><div>{displayedHadithIds.flatMap((id) => { const record = getHadithByIdForLocale(id, locale); return record ? [<article key={id}><small>HadeethEnc #{id}</small><h3><Link href={`/hadith/${id}`}>{record.title}</Link></h3></article>] : []; })}</div>{hadithPageCount > 1 ? <><p>{tr ? `${concept.hadithIds.length.toLocaleString('tr-TR')} kayıt · ${hadithPage}/${hadithPageCount}. sayfa` : `${concept.hadithIds.length.toLocaleString('en-US')} records · page ${hadithPage} of ${hadithPageCount}`}</p><nav className="concept-pagination" aria-label={tr ? 'Hadis kayıt sayfaları' : 'Hadith record pages'}>{hadithPage > 1 ? <Link href={pageHref(versePage, hadithPage - 1, 'hadiths')}>← {tr ? 'Önceki hadisler' : 'Previous hadiths'}</Link> : <span />}{hadithPage < hadithPageCount ? <Link href={pageHref(versePage, hadithPage + 1, 'hadiths')}>{tr ? 'Sonraki hadisler' : 'Next hadiths'} →</Link> : null}</nav></> : null}</section> : null}
          {people.length > 0 ? <section className="concept-related" aria-labelledby="people-title"><h2 id="people-title">{tr ? 'Bu kavramla bağlantılı kişiler' : 'People connected to this concept'}</h2><p>{people.map((person, index) => <span key={person.slug}>{index > 0 ? ' · ' : ''}<Link href={getPersonHref(person)}>{getPersonName(person, locale)}</Link></span>)}</p></section> : null}
          <section className="concept-related" id="related" aria-labelledby="related-title">
            <h2 id="related-title">{tr ? 'İlgili kavramlar' : 'Related concepts'}</h2>
            <p>{related.map((record, index) => <span key={record.slug}>{index > 0 ? ' · ' : ''}<Link href={getConceptHref(record)}>{getConceptTitle(record, locale)}</Link></span>)}</p>
          </section>
        </article>
        <aside className="wiki-infobox concept-infobox">
          <h2>{getConceptTitle(concept, locale)}</h2>{concept.arabic ? <p lang="ar" dir="rtl">{concept.arabic}</p> : null}
          <dl><div><dt>{tr ? 'Makale türü' : 'Article type'}</dt><dd>{concept.kind === 'keyword' ? (tr ? 'Külliyat etiketi' : 'Corpus tag') : (tr ? 'Kavram' : 'Concept')}</dd></div><div><dt>{tr ? 'Ayet kayıtları' : 'Verse records'}</dt><dd>{concept.verseRefs.length}</dd></div><div><dt>{tr ? 'Hadis kayıtları' : 'Hadith records'}</dt><dd>{concept.hadithIds.length}</dd></div></dl>
          <Link href="/concepts">{tr ? 'Kavram dizinine dön' : 'Return to concept index'}</Link>
        </aside>
      </div>
    </main>
  );
}
